

export function getTranslate() {
    return {
        "category": "категорія",
        "origin_name": "назва походження",
        "proteins": "білки",
        "fats": "жири",
        "water": "вода",
        "ash": "зола",
        "vitamin_b1_thiamine": "вітамін В1_тіамін",
        "vitamin_b2_riboflavin": "вітамін В2_рибофлавін",
        "potassium_k": "калій",
        "calcium_ca": "кальцій",
        "magnesium_mg": "магній",
        "sodium_na": "натрій",
        "sulfur_s": "сірка",
        "phosphorus_p": "фосфор",
        "iron_fe": "залізо",
        "manganese_mn": "марганець",
        "copper_cu": "мідь",
        "selenium_se": "селен",
        "zinc_zn": "цинк",
        "cholesterol": "холестерин",
        "saturated_fatty_acids": "насичені жирні_кислоти",
        "palmitic_acid": "пальмітинова кислота",
        "stearic_acid": "стеаринова кислота",
        "monounsaturated_fatty_acids": "одноненасичені жирні_кислоти",
        "polyunsaturated_fatty_acids": "багатоненасичені жирні_кислоти",
        "linoleic_acid": "лінолева кислота",
        "linolenic_acid": "ліноленова кислота",
        "omega_3_fatty_acids": "омега 3_жирні_кислоти",
        "omega_6_fatty_acids": "омега 6_жирні_кислоти",
        "translated_name": "перекладена назва"
    }
}

export  function getTransalteV2() {
    return {
        "category": "Категорія",
        "origin_name": "Назва походження",
        "proteins": "Білки",
        "fats": "Жири",
        "water": "Вода",
        "ash": "Зола",
        "vitamin_b1_thiamine": "Вітамін B1 (Тіамін)",
        "vitamin_b2_riboflavin": "Вітамін B2 (Рибофлавін)",
        "vitamin_b4_choline": "Вітамін B4 (Холін)",
        "vitamin_b5_pantothenic_acid": "Вітамін B5 (Пантотенова кислота)",
        "vitamin_b6_pyridoxine": "Вітамін B6 (Піридоксин)",
        "vitamin_b9_folate": "Вітамін B9 (Фолієва кислота)",
        "vitamin_b12_cobalamin": "Вітамін B12 (Кобаламін)",
        "vitamin_e_alpha_tocopherol": "Вітамін E (Альфа-токоферол)",
        "vitamin_h_biotin": "Вітамін H (Біотин)",
        "vitamin_pp_ne": "Вітамін PP (Ніацин еквівалент)",
        "potassium_k": "Калій",
        "calcium_ca": "Кальцій",
        "magnesium_mg": "Магній",
        "sodium_na": "Натрій",
        "sulfur_s": "Сірка",
        "phosphorus_p": "Фосфор",
        "chlorine_cl": "Хлор",
        "iron_fe": "Залізо",
        "iodine_i": "Йод",
        "cobalt_co": "Кобальт",
        "manganese_mn": "Марганець",
        "copper_cu": "Мідь",
        "molybdenum_mo": "Молібден",
        "fluorine_f": "Фтор",
        "chromium_cr": "Хром",
        "zinc_zn": "Цинк",
        "cholesterol": "Холестерин",
        "saturated_fatty_acids": "Насичені жирні кислоти",
        "palmitic_acid": "Пальмітинова кислота",
        "stearic_acid": "Стеаринова кислота",
        "monounsaturated_fatty_acids": "Мононенасичені жирні кислоти",
        "polyunsaturated_fatty_acids": "Багатоненасичені жирні кислоти",
        "linoleic_acid": "Лінолева кислота",
        "linolenic_acid": "Ліноленова кислота",
        "omega_3_fatty_acids": "Омега-3 жирні кислоти",
        "omega_6_fatty_acids": "Омега-6 жирні кислоти",
        "translated_name": "Перекладена назва",
        "carbohydrates": "Вуглеводи",
        "dietary_fiber": "Харчові волокна",
        "trans_fats": "трансжири"
    }
}
